name: ROS industrial ci
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  industrial_ci:
    name: ${{ matrix.ROS_DISTRO.NAME }} | ${{ matrix.ROS_REPO }}${{ matrix.PLATFORM == 'rhel' && ' (RHEL)' || ' (UBUNTU)' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        PLATFORM: [ubuntu, rhel]
        ROS_DISTRO:
          - NAME: noetic
            DOWNSTREAM_WORKSPACE: "github:UniversalRobots/Universal_Robots_ROS_Driver#master"
            CLANG_TIDY: ""
          - NAME: humble
            DOWNSTREAM_WORKSPACE: "github:UniversalRobots/Universal_Robots_ROS2_Driver#humble"
            CLANG_TIDY: ""
          - NAME: jazzy
            DOWNSTREAM_WORKSPACE: "github:UniversalRobots/Universal_Robots_ROS2_Driver#jazzy"
            CLANG_TIDY: ""
          - NAME: kilted
            DOWNSTREAM_WORKSPACE: "github:UniversalRobots/Universal_Robots_ROS2_Driver#main"
            CLANG_TIDY: ""
          - NAME: rolling
            DOWNSTREAM_WORKSPACE: "github:UniversalRobots/Universal_Robots_ROS2_Driver#main"
            CLANG_TIDY: pedantic
        ROS_REPO:
          - main
          - testing

        exclude:
          - PLATFORM: rhel
            ROS_DISTRO:
              NAME: noetic
              DOWNSTREAM_WORKSPACE: "github:UniversalRobots/Universal_Robots_ROS_Driver#master"
              CLANG_TIDY: ""

    env:
      DOCKER_RUN_OPTS: "-v /var/run/docker.sock:/var/run/docker.sock --network ursim_net"
    steps:
      - uses: actions/checkout@v6
      - run: docker network create --subnet=192.168.56.0/24 ursim_net
        if: ${{ !env.ACT }}
      - name: Platform-specific configuration
        id: config
        run: |
          if [ "${{ matrix.PLATFORM }}" = "rhel" ]; then
              echo "docker_image=ghcr.io/ros-controls/ros:${{ matrix.ROS_DISTRO.NAME }}-rhel" >> $GITHUB_OUTPUT
              echo "additional_pkgs_name=ADDITIONAL_RPMS" >> $GITHUB_OUTPUT
              echo "additional_pkgs_values=nmap-ncat" >> $GITHUB_OUTPUT
              echo "os_name=rhel" >> $GITHUB_OUTPUT
              echo "os_code=8" >> $GITHUB_OUTPUT

          else
            echo "additional_pkgs_name=ADDITIONAL_DEBS" >> $GITHUB_OUTPUT
            echo "additional_pkgs_values=docker.io netcat-openbsd" >> $GITHUB_OUTPUT
          fi

      - name: industrial_ci (RHEL)
        if: ${{ matrix.PLATFORM == 'rhel' }}
        uses: ros-industrial/industrial_ci@master
        env:
          IMMEDIATE_TEST_OUTPUT: true
          DOWNSTREAM_CMAKE_ARGS: -DUR_ROBOT_DRIVER_BUILD_INTEGRATION_TESTS=ON
          DOWNSTREAM_WORKSPACE: ${{ matrix.ROS_DISTRO.DOWNSTREAM_WORKSPACE }}
          ROS_DISTRO: ${{ matrix.ROS_DISTRO.NAME }}
          ROS_REPO: ${{ matrix.ROS_REPO }}
          CLANG_TIDY: ${{ matrix.ROS_DISTRO.CLANG_TIDY }}
          DOCKER_IMAGE: ${{ steps.config.outputs.docker_image }}
          OS_NAME: ${{ steps.config.outputs.os_name }}
          OS_CODE_NAME: ${{ steps.config.outputs.os_code }}
          ${{ steps.config.outputs.additional_pkgs_name }}: ${{ steps.config.outputs.additional_pkgs_values }}

      - name: industrial_ci (Ubuntu)
        if: ${{ matrix.PLATFORM == 'ubuntu' }}
        uses: ros-industrial/industrial_ci@master
        env:
          IMMEDIATE_TEST_OUTPUT: true
          DOWNSTREAM_CMAKE_ARGS: -DUR_ROBOT_DRIVER_BUILD_INTEGRATION_TESTS=ON
          DOWNSTREAM_WORKSPACE: ${{ matrix.ROS_DISTRO.DOWNSTREAM_WORKSPACE }}
          ROS_DISTRO: ${{ matrix.ROS_DISTRO.NAME }}
          ROS_REPO: ${{ matrix.ROS_REPO }}
          CLANG_TIDY: ${{ matrix.ROS_DISTRO.CLANG_TIDY }}
          ${{ steps.config.outputs.additional_pkgs_name }}: ${{ steps.config.outputs.additional_pkgs_values }}
